services:
  tesseract:
    image: tesseractshadow/tesseract4re:latest
    container_name: tesseract
    platform: linux/amd64  # Specify the platform
    ports:
      - "9090:9090"
    volumes:
      - ./temp/uploaded_files:/input
      - ./temp/resultats_reconnaissance:/output
    networks:
      - shared-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  shared-network:
#    external: true